/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafico;

import enlace.Puente;
import estructuras.AVLB;
import estructuras.Archivo;
import estructuras.Hash;
import estructuras.NodoAVLB;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Date;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeNode;
/**
 *
 * @author Chriss Ramos
 */
public class Administrador extends javax.swing.JFrame {

    
    
    public DefaultTableModel modeloC;
    public DefaultTableModel modeloI;
    
    public Administrador() {
        //treePrincipal.removeAll();
        initComponents();
        modeloC = new DefaultTableModel();
        modeloC.addColumn("Usuario");
        modeloC.addColumn("Pass");
        this.tablaCorrecta.setModel(modeloC);
        
        modeloI = new DefaultTableModel();
        modeloI.addColumn("Usuario");
        modeloI.addColumn("Motivo");
        this.tablaIncorrecta.setModel(modeloI);
        
        //modelo del JTree
        DefaultTreeModel model = (DefaultTreeModel) treePrincipal.getModel();
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
        
        root.removeAllChildren();
        root.setUserObject("/");
        DefaultTreeCellRenderer render= (DefaultTreeCellRenderer)treePrincipal.getCellRenderer();
        render.setLeafIcon(new ImageIcon(getClass().getResource("/reportes/documento.png")));
        render.setOpenIcon(new ImageIcon(getClass().getResource("/reportes/carpetaAbierta.png")));
        render.setClosedIcon(new ImageIcon(getClass().getResource("/reportes/carpetaCerrada.png")));
        model.reload();
        
        
        //model.setRoot(null);
        
        
        this.setLocationRelativeTo(null);
        
        //DefaultTableModel modeloI = (DefaultTableModel) tablaIncorrecta.getModel();
        
    }

/**
     * Creates new form Administrador
     */
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCorrecta = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaIncorrecta = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        btnVerHash = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        treePrincipal = new javax.swing.JTree();
        jSeparator3 = new javax.swing.JSeparator();
        lblSeleccion = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Administrador");

        jButton1.setText("Carga Masiva");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reportes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tablaCorrecta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(tablaCorrecta);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Usuarios Insertados Correctamente");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Usuarios No Insertados");

        tablaIncorrecta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaIncorrecta);

        jLabel4.setText("Carpetas");

        jButton3.setText("Crear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Modificar");

        jButton5.setText("Eliminar");

        jButton6.setText("Subir");

        jLabel5.setText("Archivos");

        jButton7.setText("Crear");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Modificar");

        jButton9.setText("Eliminar");

        jButton10.setText("Subir");

        jButton11.setText("Generar Hash");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        btnVerHash.setText("Ver Hash");
        btnVerHash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerHashActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(treePrincipal);

        lblSeleccion.setText("Seleccion");

        jButton12.setText("Carga Masiva");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Hijos");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("Generar AVL");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("Ver AVL");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton8)
                                    .addComponent(jButton9)
                                    .addComponent(jButton10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton2)
                                        .addComponent(jLabel4)
                                        .addComponent(jButton3)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                        .addComponent(jButton4)
                                        .addComponent(jButton5)
                                        .addComponent(jButton6)
                                        .addComponent(jSeparator2))
                                    .addComponent(jLabel5)
                                    .addComponent(jButton1)
                                    .addComponent(jButton7)
                                    .addComponent(jButton12))
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSeleccion)
                                    .addComponent(jButton13)))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnVerHash))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton15)
                                    .addComponent(jButton14))))
                        .addGap(0, 273, Short.MAX_VALUE)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6)
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 51, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(310, 310, 310)
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton12))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSeleccion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8)
                            .addComponent(jButton13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton10)
                        .addGap(35, 35, 35)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton11)
                            .addComponent(jButton14))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerHash)
                    .addComponent(jButton15))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String aux;
        
        String texto = "";
        JFileChooser file=new JFileChooser();
        file.showOpenDialog(this);
        /**abrimos el archivo seleccionado*/
        File abre=file.getSelectedFile();
        try {
            //System.out.println("Nombre de abre: " + abre.getPath());
            BufferedReader csvReader = new BufferedReader(new FileReader(abre.getPath()));
            String row;
            while((row = csvReader.readLine()) != null){
                String[] data = row.split(",");
                System.out.println("Dato:" + data[0] + " " + data[1] );
                
                if(data[1].length() < 8){
                    data[1] = "Contrasenia corta";
                    modeloI.addRow(data);
                }else{
                    //enviar aqui a hash
                    String v = data[0];
                    if(v.equals("﻿Usuario")){
                        System.out.println("no se agregara campo");
                    }else{
                        
                        Puente.agregar(data[0], data[1]);
                        //modeloC.addRow(data);
                    }
                    
                }
                
                System.out.println("------------------------");
                        
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        Puente.graficarHash();
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void btnVerHashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerHashActionPerformed
        // TODO add your handling code here:
        try {
            Thread.sleep(500);
        } catch (InterruptedException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        ventanaImagen vI = new ventanaImagen();
        ImageIcon img = new ImageIcon(getClass().getResource("/reportes/graficaHash.jpg"));
        
        int h = img.getIconHeight();
        int w = img.getIconWidth();
        
        
        Image imagen = img.getImage();
        ImageIcon iconoEscalado = new ImageIcon (imagen.getScaledInstance(w,h,Image.SCALE_AREA_AVERAGING));
        
        
        vI.label1.setIcon(iconoEscalado);
        vI.scroll1.setViewportView(vI.label1);
        
        vI.setVisible(true);
    }//GEN-LAST:event_btnVerHashActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String entradaUsuario = JOptionPane.showInputDialog("Nombre de Carpeta:");
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) treePrincipal.getSelectionPath().getLastPathComponent();
        DefaultMutableTreeNode newNode = new DefaultMutableTreeNode(entradaUsuario);
        selectedNode.add(newNode);
        DefaultTreeModel model = (DefaultTreeModel)treePrincipal.getModel();
        model.reload();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here: // crear archivo
        String nombreArchivo = JOptionPane.showInputDialog("Nombre de Archivo con extension:");
        String contenidoArchivo = JOptionPane.showInputDialog("Contenido del archivo: ");
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) treePrincipal.getSelectionPath().getLastPathComponent();
        DefaultMutableTreeNode newNode = new DefaultMutableTreeNode(nombreArchivo);
        selectedNode.add(newNode);
        DefaultTreeModel model = (DefaultTreeModel)treePrincipal.getModel();
        model.reload();
        String[] tokens = new String[2];
        //ahora separar el nombre de la extension
        if(nombreArchivo.contains(".")){
            System.out.println("si contiene punto: " + nombreArchivo);
            System.out.println("tamanio string: " + nombreArchivo.length());
            
            StringTokenizer st = new StringTokenizer(nombreArchivo,".");
            
            int contadorarr= 0;
            while (st.hasMoreTokens()){
                    //System.out.println (st.nextToken());
                    tokens[contadorarr] = st.nextToken().toString();
                    contadorarr++;
            
            }
            
            
                
            Archivo a = new Archivo();
            Date d = new Date();
            String fecha =d.toString();
            System.out.println("-----------------------------");
            System.out.println("NOMBRE CREADO: " + tokens[0]);
            System.out.println("EXT CREADO: " + tokens[1]);
            System.out.println("-----------------------------");
            a.setNombre(tokens[0]);
            a.setExtension(tokens[1]);
            a.setTimestamp(fecha);
            a.setContenido(contenidoArchivo);
            Puente.archivosT[Puente.contadorArchivos] = a;
            Puente.contadorArchivos++;
            
            
            /*String del = "."; 
            String[] separador = nombreArchivo.split(del);
            //System.out.println("parte 1"+separador[0]);
            System.out.println("tamanio: "+ separador.length);
            for (int i = 0; i < separador.length; i++) {
                System.out.println(separador[i]);
            }*/
            
        }
        
        //
        
        
        //a.setNombre(separador[0]);
        //a.setExtension(separador[1]);
        //a.setContenido(contenidoArchivo);
        //a.setTimestamp(fecha);
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String aux;
        
        String texto = "";
        JFileChooser file=new JFileChooser();
        file.showOpenDialog(this);
        /**abrimos el archivo seleccionado*/
        File abre=file.getSelectedFile();
        try {
            //System.out.println("Nombre de abre: " + abre.getPath());
            BufferedReader csvReader = new BufferedReader(new FileReader(abre.getPath()));
            String row;
            while((row = csvReader.readLine()) != null){
                String[] data = row.split(",");
                System.out.println("Dato:" + data[0] + " " + data[1] );
                
                if(data[1].length() < 8){
                    data[1] = "Contrasenia corta";
                    modeloI.addRow(data);
                }else{
                    //enviar aqui a hash
                    String v = data[0];
                    if(v.equals("﻿Usuario")){
                        System.out.println("no se agregara campo");
                    }else{
                        
                        Puente.agregar(data[0], data[1]);
                        //modeloC.addRow(data);
                    }
                    
                }
                
                System.out.println("------------------------");
                        
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        //hijos
        //String nombreArchivo = JOptionPane.showInputDialog("Nombre de Archivo con extension:");
        
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) treePrincipal.getSelectionPath().getLastPathComponent();
       // DefaultMutableTreeNode newNode = new DefaultMutableTreeNode(nombreArchivo);
        //selectedNode.add(newNode);
        int cantidadHijos = selectedNode.getChildCount();
        //JOptionPane.showMessageDialog(null, "cantidad hijos: " + cantidadHijos);
        //TreeNode nodo = selectedNode.getChildAt(0);
        for (int i = 0; i < cantidadHijos; i++) {
            String nombre = selectedNode.getChildAt(i).toString();
            boolean resultado = nombre.contains(".");
            if (resultado) {
                System.out.println("Nombre Archivo: " + nombre);
                
            }else{
                System.out.println("nombre carpeta: " + nombre);
            }
            
        }
        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // GENERAR AVL
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) treePrincipal.getSelectionPath().getLastPathComponent();
       // DefaultMutableTreeNode newNode = new DefaultMutableTreeNode(nombreArchivo);
        //selectedNode.add(newNode);
        int cantidadHijos = selectedNode.getChildCount();
        //JOptionPane.showMessageDialog(null, "cantidad hijos: " + cantidadHijos);
        //TreeNode nodo = selectedNode.getChildAt(0);
        AVLB arbol = new AVLB();
        for (int i = 0; i < cantidadHijos; i++) {
            String nombre = selectedNode.getChildAt(i).toString();
            boolean resultado = nombre.contains(".");
            if (resultado) {
                //System.out.println("Nombre Archivo: " + nombre);
                for (int j = 0; j < Puente.contadorArchivos; j++) {
                    Archivo ar = Puente.archivosT[j];
                    String nombreC = ar.getNombre()+"."+ar.getExtension();
                    //System.out.println("archivo concatenado: " + nombreC);
                    if(nombreC.equals(nombre)){
                        //System.out.println("encontro archivo y su contenido es: "+ ar.getContenido());
                        //hacer avl aqui
                        
                        arbol.insertar(new NodoAVLB(ar.getNombre(),ar.getExtension(),ar.getContenido(),ar.getTimestamp()));
                    }
                }
            }else{
                System.out.println("nombre carpeta: " + nombre);
            }
            
        }
        arbol.graficar("");
        
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
         try {
            Thread.sleep(500);
        } catch (InterruptedException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        ventanaImagen vI = new ventanaImagen();
        ImageIcon img = new ImageIcon(getClass().getResource("/reportes/graficaAVL.jpg"));
        
        int h = img.getIconHeight();
        int w = img.getIconWidth();
        
        
        Image imagen = img.getImage();
        ImageIcon iconoEscalado = new ImageIcon (imagen.getScaledInstance(w,h,Image.SCALE_AREA_AVERAGING));
        
        
        vI.label1.setIcon(iconoEscalado);
        vI.scroll1.setViewportView(vI.label1);
        
        vI.setVisible(true);
    }//GEN-LAST:event_jButton15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }
    
    public void agregar(){
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerHash;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblSeleccion;
    private javax.swing.JTable tablaCorrecta;
    private javax.swing.JTable tablaIncorrecta;
    private javax.swing.JTree treePrincipal;
    // End of variables declaration//GEN-END:variables
}
